### ISSUE TITLE
MarkLogic runtime typechecks

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#1506]
Implement runtime typechecks (i.e. `MapFunc.Guard`) in the MarkLogic planner.

**Comment by wemrysi** [comment]
Ideally this would happen after the move to `TypeOf`due to the ease of implementation.

**Comment by zeeiyerWork** [comment]
If your data is non-uniform:
e.g. name field is String in 90% cases and Integer in 10% + you try to concat a string to this name filed -> in case of Integer you get "undefined", so that you still get a result back (instead of failing). Today you fail. That is what this change is about.

Waiting on the underlying QScript Changes (move to TypeOf) - since this will get easier to implement, so pushing to June.
