### ISSUE TITLE
Improve compilation time of the connector project

### ISSUE THREAD

**Issue by sellout** [precog/quasar#1554]
This is still the slowest project to compile by far.

We can improve this by moving more things in the direction of `TTypes` (pulling an abstract type to some containing scope, where constraints only have to be resolved once). And @paulp probably has other suggestions, too …

**Comment by zeeiyerWork** [comment]
@djspiewak -> Are you planning to upgrade to sbt 1.0 (and/or take advantage of zinc)? What's the timeline on that? I suppose we could revisit this once that is done, assuming that is happening soon.

**Comment by alissapajer** [comment]
Looking at the release notes for `zinc` I don't see any indication that upgrading to `zinc` 1.0 will drastically improve the compilation of `connector`. We've concluded that `connector` is slow to compile because of implicit resolution, and so I don't think `zinc` 1.0 wouldn't help that much. @djspiewak did something about `zinc` 1.0 make you think it would help with this problem?

Also @djspiewak I forget, have you tried compiling `connector` with `-Yinduction-heuristics`. Did that yield any improvements?

Additionally, I'd actually like to suggest we close this issue because having a generic issue like this open isn't really helpful. Instead we should open specific issues that state _what_ we will do to attempt to improve compile times.

**Comment by jedesah** [comment]
@alissapajer I'm no expert, but my understanding is that Zinc is more aggressive about determining which files really do need to be recompiled. If fewer files in `connector` are re-compiled every time we make a small change in `connector` or elsewhere then Zinc could be a big win to overall productivity

**Comment by alissapajer** [comment]
@jedesah yeah that's how I understand it as well. I don't know enough about how it decides what to recompile to say if it will help our problem here, but it definitely would be great if it did!
