### ISSUE TITLE
Incremental timings included with PhaseResults

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#1868]
We'd like to time how long we spend computing each `PhaseResult`. 

When `PhaseResults` print in the REPL, we'd print the timing of each phase along with the `RenderTree`. If we're not in debug mode, we'd print the sum of the times of each phase (not just the time of the last phase).

(Note to self: does anything of value happen _not_ during a `PhaseResult`?)

This will greatly aid in debugging performance issues in queries as we'll know which phases are the culprits just by running the query in the REPL.

**Comment by sellout** [comment]
“does anything of value happen not during a `PhaseResult`?” – Yes. The actual query evaluation. Currently the REPL prints out how long the query took and I’m not sure whether that includes all the compilation time or not. Also not sure if it includes the time to read the results. Ideally, we should have a time for when we first get a cursor back (in Mongo, this can actually take a while, I think, because we sometimes need to make multiple sequential requests, and we don’t get a cursor until the final request is made after the others have actually completed), and a time when we first get results back.
