### ISSUE TITLE
MongoDB aggregation should perform $match before $unwind

### ISSUE THREAD

**Issue by damonLL** [precog/quasar#1880]
- SlamData Community 4.0.10
- MongoDB 3.0.1
- Windows OS

The following SQL² query takes 15 minutes to execute in user's environment.  Collection size is ~ 200K documents and 5GB total data size.

```
SELECT measureEnrollments[*].measureKey
FROM memberMeasures
WHERE year=2017 and memberNumber="123456"
```

It results in the following MongoDB aggregation request:

```
db.memberMeasures.aggregate(
  [
    {
      "$project": {
        "__tmp4": {
          "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": [] }, "$measureEnrollments"] },
                {
                  "$lt": ["$measureEnrollments", { "$literal": BinData(0, "") }]
                }]
            },
            "$measureEnrollments",
            { "$literal": [undefined] }]
        },
        "__tmp5": "$$ROOT"
      }
    },
    { "$unwind": "$__tmp4" },
    {
      "$match": {
        "$and": [
          { "__tmp5.year": NumberInt("2017") },
          { "__tmp5.memberNumber": "123456" }]
      }
    },
    { "$project": { "value": "$__tmp4.measureKey", "_id": false } }],
  { "allowDiskUse": true });

```

I believe the `$match` phase should be the first phase in the pipeline rather than second to last.  This would allow MongoDB to utilize it's indexes, which would rapidly and dramatically reduce the resulting data set that the `$unwind` phase would have to process.

**Comment by damonLL** [comment]
As a point of reference: when the MongoDB query was changed manually in the Mongo shell, and the order operations were changed as suggested, the query returned immediately with correct results.

**Comment by emptyslot** [comment]
Another example of this if it helps:
Quasar release 14.5.7, Linux (Ubuntu 12.04. Also tried 16.04), OpenJRE
MongoDB backend: 3.2.10

Collection size: ~1600 documents

Query:
`SELECT objects.uri, objects.info.id FROM objects WHERE objects.annotations[*].project_id = "some_project_id"`

Document structure:
`{
  uri: "xxx", 
  "info": {"id": "yyy"},
  "annotations": [
    {
      "project_id": "zzz", ..
    }, ...
  ]}`

This query takes about 38 seconds to complete. Upon inspection of the aggregation generated, it looks like this:
`db.objects.aggregate(
  [
    {
      "$project": {
        "__tmp4": {
          "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": [] }, "$annotations"] },
                { "$lt": ["$annotations", { "$literal": BinData(0, "") }] }]
            },
            "$annotations",
            { "$literal": [undefined] }]
        },
        "__tmp5": "$$ROOT"
      }
    },
    { "$unwind": "$__tmp4" },
    { "$match": { "__tmp4.project_id": "some_project_id" } },
    {
      "$project": {
        "uri": "$__tmp5.uri",
        "id": {
          "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": {  } }, "$__tmp5.info"] },
                { "$lt": ["$__tmp5.info", { "$literal": [] }] }]
            },
            "$__tmp5.info.id",
            { "$literal": undefined }]
        },
        "_id": false
      }
    }],
  { "allowDiskUse": true });
`

Like mentioned by @damonLL this could also use a $match at the beginning stage of the pipeline. With the $match manually added and tried in mongo shell, the query only takes about 1.8 seconds

**Comment by jdegoes** [comment]
@zeeiyerWork Let's make sure this doesn't slip past June. It's a customer request causing some pain.

**Comment by emptyslot** [comment]
Thanks @jdegoes and @zeeiyerWork

**Comment by sellout** [comment]
This is fixed in new Mongo.

**Comment by sellout** [comment]
Actually, to clarify, this is fixed in _QScript_, so all QScript connectors will filter before unwinding if the filter doesn’t reference the flattened values.

**Comment by emptyslot** [comment]
@sellout In the case above, the filter is using the flattened values though. Did you mean to say that the fix will not add a $match at the first stage for the above example?

**Comment by jdegoes** [comment]
@sellout The behavior we need is as much of the filter as can be pushed to the beginning _is_ pushed to the beginning, while the remainder can occur after the unwind.

**Comment by sellout** [comment]
Yes, thanks for the clarification @emptyslot and @jdegoes – I retract my assertion.

It’s only @damonLL’s original query that is fixed. It’s true that we should pull as much of a filter as possible ahead of an unwind.

@emptyslot I’m not sure how your query can have the `$match` first. As of MongoDB 3.2, we could take advantage of the `$filter` operator, and do something like:
```json
[{ "$project": {
     "uri": "$objects.uri",
     "id": "$objects.info.id",
     "__tmp0": { "$filter": ["$objects.annotations", "tmp", { "$eq": ["$$tmp.project_id", "some_project_id"] }] } } },
 { "$unwind": "$__tmp0" },
 { "$project": { "uri": true, "id": true, "_id": false } }]
```
Is that what you mean, or am I missing some other approach?

**Comment by emptyslot** [comment]
@sellout The idea is to use a match stage in the beginning with an $elemMatch on the array that we're unwinding such that the match stage eliminates all documents whose arrays do not contain our predicate. I don't have that manually written aggregate handy, but I can provide that tomorrow if you want.

**Comment by sellout** [comment]
@emptyslot I _think_ that’s a different query … or, at least in that case, we’d have to first `$match` with `$elemMatch`, which eliminates some records, then `$unwind`, then `{ "$match": { "__tmp4.project_id": "some_project_id" } }` to filter on the remaining records.

_Only_ using `$elemMatch`, we would get one result for each input field, but the query as stated would give us _n_ duplicate results in the case where one document had _n_ elements with a matching project_id in the annotations array.

**Comment by jdegoes** [comment]
@sellout In cases where we can filter _some_ things out, but not everything (e.g. due to MongoDB's "any" semantics with arrays), we should definitely try to do that, knowing that after unwind (etc.) we can perform additional filtering to eliminate all the non-matching elements.

**Comment by sellout** [comment]
Cool, so I’ll handle this as a few things:

- [ ] push parts of a filter that don’t refer to the flattened field _before_ the $unwind (this is a QScript change)
- [ ] duplicate other filter components before the $unwind to pre-filter arrays that don’t match at all (this is a Mongo change).
- [ ] on 3.2+ use `$filter` before the unwind (this will be a QScript change to allow “dimensional operations” directly on arrays in MapFunc, and a Mongo change to handle the `FilterArray` MapFunc that’ll be added by the QScript change).

**Comment by jdegoes** [comment]
Sounds awesome. 👍

**Comment by emptyslot** [comment]
@sellout @jdegoes Thanks guys! Just to make sure we're on the same page:

@sellout You were right in your comment that we can't use only $elemMatch. My idea was to use $elemMatch to pre-filter (at the first stage of pipeline using match) documents in which the arrays won't match the predicate after unwinding anyway. This is the only stage where MongoDB can use indexes to make aggregation faster. Then, unwind and after the unwind stage, essentially, apply the same filter to eliminate unwound items from the array that don't match the (same) predicate. Note that the set of items that will be filtered will be much less in this case because of the first stage match doing $elemMatch.

I hope I've not confused things further :)

**Comment by wemrysi** [comment]
@sellout @jdegoes It would seem that pre-filtering arrays could also be handled as a `QScript` change via another new MapFunc for arrays, `ArrayExists`. All mongo versions would support `ArrayExists` via `$elemMatch` and then post-filter the unwound values and 3.2+ would additionally support `FilterArray` via `$filter` which would eliminate the need for the post-filter.

**Comment by jdegoes** [comment]
@wemrysi 

This can already be accomplished without any `QScript` changes.

`ArrayExists` can be emulated with `EXISTS(array[_].foo > 2)`, where `EXISTS` is the normal SQL reduction that returns true if at least one element of the set is true. So if it would be helpful, perhaps QScript can generate these in order to pull up additional pieces of a filter earlier in the pipeline.

**Comment by wemrysi** [comment]
@jdegoes Yes, that's true but every connector would still then have to recognize that pattern and translate it into an array-level operation. To clarify things a bit, `ArrayExists` and `FilterArray` are optional operations that connectors with support for array-level operations can utilize in their implementation, they aren't something that would be exposed via SQL^2 (see #2449 for some detail). I was just suggesting that we handle what was described as a mongo-specific task (pre-filtering arrays for existence) in a more general way such that any connector with capability for array-level operations could benefit.

**Comment by jdegoes** [comment]
@wemrysi 

What you propose makes it more difficult, not easier, to support new connectors, since _every_ connector must support `EXISTS(array[_].foo > 2)`. So if they all have to support that, then making them _also_ support `ArrayExists` will be more work, not less.

Additionally, if a connector has support for array-level operations, then if a user specifies a query like `EXISTS(array[_].foo > 2)`, then of course we would want to accelerate that by using the connector's native support for this operation, rather than utilizing a slow, suboptimal way of implementing the query.

If we want to detect and accelerate that in backends that support array-level operations, then it makes more sense, in my opinion, to not natively support these as `MapFunc`s, since that doesn't really solve the general problem but is a hack around the lack of a general solution.

That's my 2 cents anyway.

**Comment by jdegoes** [comment]
That said I don't have major preference since you can introduce a combinator for translating `ArrayExists` to ordinary SQL2, but it still means if a connector relies on this approach, it will fail to optimize user-land queries.

**Comment by wemrysi** [comment]
@jdegoes 

No connector will ever _have_ to support `ArrayExists`, array-level capabilities are just that, a capability which some may have and others not.

As you say, all connectors must support `EXISTS(array[_].foo > 2)`, which would be translated to a `QScript` representation involving a reduction, left-shift and a filter, if I'm not mistaken. However, if a connector indicates to the QScript compiler that it has the capability for array-level operations, then, instead of the operations I mentioned, the connector would receive an optimized QScript program equivalent to (pseudocode) `ArrayExists(array, _.foo > 2)` obviating the need for that connector to detect these sorts of patterns in its own implementation.

Thus only those connectors that indicate support/desire for such array-level operations will ever see them used in a QScript program. This is the same concept as with `FilterArray` mentioned above.

Does this clarify things or have I missed your point?

**Comment by jdegoes** [comment]
@wemrysi I think I understand now, and if it's totally opt-in on a per-connector basis, and also optimizes user-land queries that effectively do the same, it makes total sense. 👍

**Comment by jsantos17** [comment]
@beckyconning This is an important issue we can start tackling now. Changes won't be visible until QScript filter bubbing is done, but we can make sure the Mongo connector plans the expected QScript correctly.
