### ISSUE TITLE
Reduce wildcard imports

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#1938]
Specifically, wildcard imports that grab an enormous mess of implicit conversions.  The most common offender:

```scala
import scalaz._, Scalaz._
```

Also, wildcard imports do make it difficult to figure out where certain types are coming from (see, @alissapajer, I *have* learned my lesson on that one!).  But more significantly, bringing in a mess of unused implicits slows down the compiler considerably.  This is most noticeable in files where there is already a complex set of resolutions to perform (such as anything involving `Inject`).  Scala's implicit resolution is exponential in the number of implicits in scope.  The easiest way to make it faster is to reduce the scope.

This isn't a magic-bullet solution to compile times, but it absolutely contributes to the problem.

**Comment by sellout** [comment]
There was a time when we went through and replaced `Scalaz._` with smaller imports, but we didn’t find a significant change in compile time (granted, the code base has gotten a lot larger since then).

I find many imports tough to manage (you spend a lot of time thinking “why can’t it find `>>=`?!”) to the point where we’ve discussed moving much of Scalaz to our Predef. As far as figuring out where identifiers are coming from, Ensime is a great help with that. Duplicating information the compiler knows (and can quickly tell you) is not one of my favorite things.

So, until we have some numbers that show a speedup that justifies the extra management, I’m not in favor of this.

**Comment by djspiewak** [comment]
I'll give it a shot with a couple good exemplars.  Basically, there won't be a significant change in files that lack a lot of implicit falsification, but there will be for any file that involves inductive search, since every theorem brought into scope has to be individually falsified at each level of the tree.  Scala needs a cut operator…

**Comment by fommil** [comment]
@sellout @djspiewak don't forget to use [`addEnsimeScalaPlugin`](http://ensime.org/build_tools/sbt/#customise) on projects that use compiler plugins... maybe that's why it's always been bust in your wacky projects? This should be automatically fixed in https://github.com/ensime/ensime-server/pull/1786 and will hopefully make ensime immediately more useful for advanced devs who didn't know this trick.

**Comment by djspiewak** [comment]
@fommil Ah that's cool!  I didn't realize you could do that.  I need to loop around again to try Ensime once more, especially given things like this.  How well does Ensime do with TLS?

**Comment by fommil** [comment]
I was using it in https://github.com/fommil/drone-dynamic-agents perfectly fine.

You'll definitely like the next entry in the plan, which is our sponsored dev is going to revamp the sublime plugin! Hopefully it'll make it simpler and easier to maintain. The launcher is probably launching the wrong version of the server right now (should be `2.0.0-SNAPSHOT` but I bet it's using `1.0.1`)
