### ISSUE TITLE
TYPE_OF("") = "array"?

### ISSUE THREAD

**Issue by garyb** [precog/quasar#2065]
This was specced in #1802, but it seems a bit wrong? Although `||` works for concatenation you can't really treat it like an array, as projections like `[*]` do not work. In the documentation `String` is treated as a separate type everywhere too, with its own set of operators for regex and the like.

This will present some problems for the structure viewer/editor, as if a group by type is applied, it will result in array and string values being conflated in the resulting grouping.

**Comment by jdegoes** [comment]
@garyb A lot of stuff is "caught in the middle". Ideally a string would literally be an array of "code points" (abstract characters, not bytes or anything else), but not all that machinery is in place, which is why logical things like `"a"[0]` and `COUNT("abcd"[_])` don't work (yet).

Maybe until they really are treated as arrays, `TYPEOF("") = "string"`?

**Comment by zeeiyerWork** [comment]
@drostron -> Please see above comments. seems we need to implement `TYPEOF("") = "String"` for now.

**Comment by jdegoes** [comment]
What we're missing is perhaps:

`TYPEOF({} @ {"_ejson.type": <foo>}) = <foo>`

**Comment by jdegoes** [comment]
Or rather:

`TYPEOF(<foo> @ {"_ejson.type": <bar>) = <foo> @ <bar>`

This would allow you to tell that, e.g. `"hello world"` is both an array but also a string.
