### ISSUE TITLE
Improve analytic functionality in standard library

### ISSUE THREAD

**Issue by jdegoes** [precog/quasar#2198]
# Introduction

Many basic functions are missing from SQL<sup>2</sup> standard library, which makes it difficult to perform rudimentary analytics. Some of these can be written in user-code, but only with great boilerplate and expertise, increasing the difficulty of using Quasar for common analytics.

This ticket is designed to address a number of low-hanging fruit issues identified by users & customers.

To the maximum extent possible, new functions should be implemented in terms of new or existing primitives so connectors are not forced to implement new functionality. Connectors can always reverse engineer functions (or read metadata, etc.) to provide an accelerated native function.

# Math

 * `ROUND(num)`
 * `CEIL(num)`
 * `FLOOR(num)`
 * `ROUND_TO(num, position)`
 * `RADIANS(degrees)`
 * `PI()`
 * `DEGREES(radians)`
 * `LN(num)`
 * `LOG(num, base)`
 * `SIGN(num)`
 * `SQRT(num)`
 * `ACOS(x)`
 * `ASIN(x)`
 * `ATAN(x)`
 * `ATAN2(y, x)`
 * `COS(x)`
 * `COT(x)`
 * `SIN(x)`
 * `TAN(x)`
 * `ABS(x)`

# String

TBD: Decide on names for these things based on common conventions.

 * `PARSE_TIMESTAMP(text, text)` — `to_timestamp(x, y)` in Postgres
 * `PARSE_NUMBER(text, text)` — `to_number` in Postgres
 * `FORMAT_NUMBER(double precision, text` — `to_char` in Postgres
 * `INITCAP(string)`
 * `LEFT(string, num)`
 * `RIGHT(string, num)`
 *  `LTRIM(string [, characters])`
 *  `RTRIM(string [, characters])`
 * `TRIM([leading | trailing | both] [characters] from string)`

Probably some of these should be array functions or aliases for array functions.

# Date/Time

 - [X] `TIME_OF_DAY` — Extract time from timestamp
 - ??? — Extract date from timestamp
 - ??? — Extract all possible components from time
 - `DATE_PART` — Extract all possible components from date
 - ??? — Construct timestamp from time and date
 - ??? — Construct time from components
 - ??? — Construct date from components
 - `NOW()`

**Comment by jdegoes** [comment]
@damonLL I got some of the functions we discussed. Please reply to this issue to include more.

**Comment by sellout** [comment]
Just some comments about which parts of this (at least partially) exist:

## String

* `to_timestamp` exists, but converts epoch millis. `timestamp` parses an ISO 8601 timestamp (same with `date` and `time`)
* `to_string` converts any non-structural value to a `String` (but without any user control over the format)

## Date/Time

* `time_of_day` extracts a time from a timestamp
* `temporal_trunc("day", ts)` (synonymously `date_trunc`) _zeros_ the time component (but returns a `Timestamp`, not a `Date`)
* `date_part` (synonymously `temporal_part`) maps to specific extractors in LP that apply to any `Temporal` value (`Date ⨿ Time ⨿ Timestamp`). Currently all the extractors are typed with a `Temporal` domain, but I think we should restrict it so that, e.g., `ExtractCentury` has `Date ⨿ Timestamp` as its domain. There is another issue specifically about which extractors should exist as primitives: #2169

**Comment by jdegoes** [comment]
@sellout I added `TIME_OF_DAY` above. The others seem to not overlap. Postgres overloads the meaning of things like `to_timestamp`, so while we have one meaning, there's the two-argument variant that we don't implement at all.

**Comment by damonLL** [comment]
That's a comprehensive list, thanks @jdegoes and @sellout! Here are just a few more I would consider adding:

## Math
* `ABS(x)`

## String
* `INITCAP(string)`
* `LEFT(string, num)`
* `RIGHT(string, num)`
*  `LTRIM(string [, characters])`
*  `RTRIM(string [, characters])`

or alternatively 

* `TRIM([leading | trailing | both] [characters] from string)`

instead of LTRIM / RTRIM.

## Date/Time
* NOW()   

The `NOW()` function is recognized in SQL² but isn't supported by any back ends yet, so perhaps it's at a different level of scope.  It is a regularly requested feature.

**Comment by jdegoes** [comment]
@damonLL Done. Thanks for the feedback!

**Comment by zeeiyerWork** [comment]
@alissapajer -> This should go high since as per Field -> "The `NOW()` function.......  gets requested on a monthly basis. .... is asking for it now". Let me know if this whole thing or what pieces of it can get accommodated before our next major release.

**Comment by alissapajer** [comment]
@zeeiyerWork so we can definitely get the `NOW()` function implemented for mongo before the next major release. Do we need `NOW()` for all backends or just for mongo?

Additionally, Is `NOW()` the only function that customers are requesting, or are there others?

**Comment by damonLL** [comment]
@alissapajer and @zeeiyerWork Thank You!  The `NOW()` function for Mongo is a great start.  Of course other connectors too when we can.

Anything dealing with date/time transformations is also regularly requested, but some of that can be handled in the pivot table and structure view/editor in SlamData, now or in the future.  I would say of all the functions listed above, any date/time related items are higher on the list, then would be string manipulations (`RIGHT`, `LEFT`, etc), then finally math. Based on frequency of requests.

**Comment by zeeiyerWork** [comment]
@alissapajer -> Let me know which of these we can accommodate. @damonLL -> I concur: (date/time manipulation, substring functions and math-functions) in that order.

**Comment by alissapajer** [comment]
@rintcius so the math operators you are working on in https://github.com/quasar-analytics/quasar/issues/2272 are lower priority than other operators, per @damonLL's comment above. If you're near done with that work, or fixing existing bugs in operators that are in master, then that work is probably worth finishing and PRing. But if not, then it's best to jump onto `NOW()` (https://github.com/quasar-analytics/quasar/issues/2502) or any other issue in the "New Mongo" epic.

**Comment by alissapajer** [comment]
@zeeiyerWork at this point I'm only comfortable committing to the `NOW()` function for new mongo. Let's see how we are progressing over the next couple weeks, and if we have the resources, I'll add an issue for date/time manipulation (followed by the string functions, followed by the math functions).

**Comment by zeeiyerWork** [comment]
@alissapajer -> I included it since @rintcius has already been working on it. Further, as per my understanding, the LOE for adding M versus N arithmetic operators (where M = some multiple of N) is low LOE (i.e. same files, lot of copy/paste/edit). So @rintcius if it is indeed low LOE, that would make a case for getting it all done. If not, we should spit it as per @alissapajer comment and break it out into operators we are supporting now (in this epic) versus later (post 4.3 epic)

**Comment by rintcius** [comment]
@alissapajer @zeeiyerWork I have a PR up for `floor` and `ceil` #2505 but I'll leave it at that. Better to focus on higher prio stuff first.

**Comment by zeeiyerWork** [comment]
@jdegoes -> An additional question that came up during implementation is the desired precision we support via SQL2, since java.lang.Math sometimes falls short. Let us know if you have any specs to add in that regard.

**Comment by jdegoes** [comment]
@zeeiyerWork MRA's data model only has integer and decimal types, but connectors are free to use fixed-size types for performance and implementation reasons.
