### ISSUE TITLE
Exploit Optional Schema (and Document Validation)

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2387]
MongoDB 3.2 and later have [optional schema,](https://docs.mongodb.com/manual/core/document-validation/) which can be used to accelerate statistical-type inference, as well as produce better error messages about broken queries.

- [ ]  Accelerate SSTs with optional schema
- [ ]  For queries over collections with schema, fail out unproductive queries
- [ ]  Remove runtime type checks when optional schema indicates they aren't necessary

**Comment by sellout** [comment]
So, more generally, we should have connectors implement a function that returns the schema (represented as an SST?) for a particular collection.

Then type checking in QScript can apply that schema to `Read` nodes, which will then automatically handle the second and third checkboxes, since we already fail queries that don’t type check and only add runtime checks for values we don’t know the type of. Right now, we just treat `Read` as `Type.Top`, so it provides no information. We simply need a way for QScript to request a more precise type for those nodes.
