### ISSUE TITLE
Working well with Mongodb Replica Sets

### ISSUE THREAD

**Issue by zeeiyerWork** [precog/quasar#2395]
Most Production Mongo deployments are executed as [replica sets.](https://docs.mongodb.com/manual/replication/)

In this case:
- Our documentation needs to be updated to advise users on how to connect with the replica set (since a primary host may go down and be taken over by a secondary). The best practice for analytics is often to run an additional hidden node that is divorced from the nodes participating in the HA play. See [this blog](https://blog.mlab.com/2016/10/configuring-a-mongodb-replica-set-for-analytics/), for example.

- Further, Mongodb allows queries to go against primary or secondary (for queries that may tolerate replication delays). Has such a requirement ever been voiced, where the end-user selectively wishes to execute some queries against Primary (for real-time data analytics) and some against Secondary (or Hidden) for queries that can tolerate delays. If so, do we need to handle it in our new Mongo connector implementation? 

@damonLL , @dugdun , @jdegoes -> Please opine.

**Comment by dugdun** [comment]
@zeeiyerWork I can definitely update the docs for connecting to a MongoDB replica set. From what I've seen we just need to list each server separately in the mount dialog.

As for doing analytics against a hidden node, I fully agree. Having the node hidden means that it can never become primary. If users are wanting to read from the hidden node then they will just need to access only that server in their MongoDB replica set and not add the primary/other secondaries in the mount configuration.

As far as replication goes, generally the replication lag is just a few seconds behind the original. This does depend on the latency between the primary and secondary nodes. I've not tried setting a read preference in SD so that a secondary is preferred, but there isn't a way that I know of in SD to force a primary read in some cases and a secondary read in others.

Let me know if that answers all your questions.

**Comment by damonLL** [comment]
Just a quick addition: we've gone through this exercise before in the past with a few customers. Primarily because of their concern with hitting the primary in production and causing performance issues.

With the MongoDB Java driver, you can specify the read preference (as @dugdun suggests). If you want all reads to go to a secondary, but all writes go to a primary, you can set `readPreference` to '[secondary](https://docs.mongodb.com/manual/reference/read-preference/#secondary)' and since we typically only do writes when working with administrative functions (rename/delete/updating workspace) this should never be noticeable in regards to performance.

**Comment by damonLL** [comment]
One thing also @dugdun: not 100% sure that SlamData would like itself to the hidden mode of the hidden mode went down. I think the driver will figure out other replica set nodes, and use other secondaries if the hidden goes down. Think it's part of the "feature set'. We need to confirm before starting authoritatively on docs, I can help if you need.

**Comment by damonLL** [comment]
Like = limit

Phone updates to GitHub and auto correct 🙁

**Comment by damonLL** [comment]
Like = limit

Phone updates to GitHub and auto correct 🙁

**Comment by zeeiyerWork** [comment]
Here are the options visually - the underlined items imho are what need to be tested or need tickets (i.e. additions to Quasar/Slamdata capability).

Of course, if it is a toy-implementation with just a single Mongo node then there is no issue.

Otherwise, it seems our best practice should be to either 
- run SD-analytics against Primary if transaction volumes are low and they can tolerate 0-delay wrt analytics (and test failover behavior) as in Option 2 in the picture
- or ask for a Hidden node to be spun up so SD-analytics can run against it (without interfering with the OLTP nodes and their failover behaviors) as in Option 1 in the picture.
- or if they want ZERO interference with OLTP cluster and want HA for Analytics Mongo Cluster, test and suggest Option 3 in the picture.

![image](https://user-images.githubusercontent.com/24783629/27524790-61c4eca8-59ed-11e7-89ff-da3e925dfa37.png)

**Comment by dugdun** [comment]
@zeeiyerWork, in option 1, you state **Run Analytics against Hidden node (Writes and Reads)**. The hidden node would have to be a secondary node, and you cannot write to secondary nodes. Only the primary can take writes. I don't know if the above was a typo or not. Also note that in option 1, if they are adding a hidden node to a three node replica set, then best practices dictate that they add another node (whether data bearing or arbiter only) so the number of nodes in the replica set is an odd number.

Using a hidden secondary node for running SlamData against would allow us to add any necessary indexes for analysis to this node, and would not require us to have them on the rest of the replica set. As I'm sure you're aware, OLTP and OLAP processes benefit from different indexes most the time. For this to work however, we would only want to mount the hidden secondary and not let SlamData read from any of the other nodes. This of course would cause problems if this node went down, but it's the same thing if any stand-alone or a replica set that we only added a single node in the mount information.

Option 3 buys the most flexibility, although it makes things more complex. By having an OLTP and an OLAP replica set, you need to have a process tail the oplog from the OLTP set and write to the OLAP set. This allows for more freedom on the OLAP set and you can continue to run analytics if a node goes down. You can also set the process that copies the data from OLTP to OLAP to rearrange data to a format that might be better suited for OLAP processing.

We can definitely test each of the different scenarios out and put documentation around them, although most shops will probably use a set up similar to option 2 above.

**Comment by zeeiyerWork** [comment]
Yes, working backwards:
>>> Option 3 buys the most flexibility, although it makes things more complex. 

Agreed that's what "lot more infrastructure work" meant. But it gives you total isolation between OLTP and Analytics Payloads, along with HA for your Analytic Payload. In this case, the most important thing to be tested is the latter HA behavior - **What does Slamdata do when the Primary of the Analytics Replica Set goes down and a Secondary node takes over.?** 

>>> Option 2

- End-user could mount Primary today it seems , but generally not a good idea to mix analytics with production-OLTP.  **We do not want to get calls stating that we allowed an analyst to bring down someone's OLTP database to its knees :-)**.
- If the end-user mounts secondary, good to test behavior and document what errors get presented to the end-user when 
--- Slamdata tries to write its artifacts
--- User tries write operation by renaming collections etc.

>>> Option 1

Agreed -> Typo. 
However wrt Odd number of instances - yes that is the preference when the node has voting rights. But by setting priority:0 and hidden:true, one can just add 1 hidden node to a 3 node-replica set. See [here](https://docs.mongodb.com/manual/core/replica-set-hidden-member/) for an example.

*******************

So: net-net
## TASK1 (@damonLL and @dugdun)
- Update documentation to describe various possible deployment scenarios (as discussed here with pros/cons)

## TASK2 @damonLL and @dugdun)
- Test to document behaviors as described in the 3 options above and document.

## TASK3 (@zeeiyerwork and @jdegoes to weigh in on prioritization)
Based on feedback from TASK1/TASK2, create specific issues - I suppose these are likely to be
### 1. Simplifying operations against a Replica-Set 
- i.e. 1 mount point where 
- Writes automatically go to Primary and 
- Reads go to Secondary/Hidden node specifically serving Analytics needs (More sophistication could also mean being able to selectively send some queries to Secondary/Hidden and some to Primary (if replication delay running long and replication delay cannot be tolerated)) 
- And optionally Slamdata artifacts get written elsewhere, given a goal of not polluting the OLTP DB (We are already taking care of this via this [issue](https://github.com/slamdata/slamdata-advanced/issues/69). See related [mocks](https://docs.google.com/drawings/d/1Zg5YRAidGL0U0s8iU81GtuCCnjKx8bkzZYFPXM1QB8k/edit)

### 2. Potential Slamdata misbehavior after failover within Replica Set
- i.e. Slamdata does not recognize the underlying changes in the mount definition, when Primary fails and another node takes over the role of Primary.
***********

**Comment by zeeiyerWork** [comment]
@dugdun -> assigned to you, assuming you are in agreement. Then hand it over back to me? once you are done with your tasks? <Thanks>

**Comment by dugdun** [comment]
@zeeiyerWork sounds good. I'll let you know once documentation and testing are complete.

**Comment by sellout** [comment]
So, I don’t have much to add here. My one question is whether @damonLL’s comment that “you can set readPreference to 'secondary'” means that we should expose `readPreference` in the connection URI. If so, please make an issue for that.

**Comment by jdegoes** [comment]
@sellout Hopefully that's already supported both in the UI and backend, as we support custom key/value pairs.

**Comment by dugdun** [comment]
It seems that even though we can use the settings area to pass in `readPreference` and a value of `secondary`, it doesn't seem that MongoDB will read from a secondary instance. I even stopped two of the three nodes so the remaining instance is forced to be a secondary node and I get a timeout error because it's trying to access the primary instance. Are we forcing the `readPreference` to be `primary`? I'll log a quasar issue about this.

It also appears that you have have a secure instance and pass in credentials if you want to pass in extra key/values via the settings interface. I'll do more testing around this to verify and enter an issue if necessary.

Until we can read from the secondary instance, I can't test that the above situations to verify that they work as expected.

**Comment by damonLL** [comment]
@dugdun there is definitely something about requiring creds if you want to pass arguments along with it. From what I recall, I was able to specify readPreference and assign it to secondary. The bulk of the processing was then performed on the secondary, with only some of the activity occurring on the primary. My *guess* is that these were perhaps updates to the workspace collection. Just wanted to provide my anecdotal response here.
