### ISSUE TITLE
Add new optional MapFunc component: MapFuncArray

### ISSUE THREAD

**Issue by sellout** [precog/quasar#2449]
These are operations like those mentioned in #2379 where we currently represent them like `Reduce(LeftShift(<some array>))`, but many connectors can handle them as mapping operations on Arrays.

I’m not sure if we need a separate component for each one, or if we can have connectors specify the set of these that they support, or some other approach, but we shouldn’t force connectors to support all of them.

Then we need QScript transformations that convert from QScript nodes to the new MapFuncs.

Some examples (not sure if these actually clarify anything):

`Map(a, ReverseArray(_))` ← `Reduce(Sort(LeftShift(a, Hole, IncludeId, RightSide), _[0]), ???, List([_[1] ...]), ReduceIndex(0.right))`
`Map(a, ReduceArray(Max(_)))` <- `Reduce(LeftShift(a, Hole, ExcludeId, RightSide), ???, List(Max(_)), ReduceIndex(0.right))`

**Comment by zeeiyerWork** [comment]
@alissapajer -> assigned to you for now. Next week, based on your guidance, we can decide, which ones can be assigned to @drostron and @wemrysi -> since they have expressed interest in learning this. Or you can just reassign some of these QScript, LP tickets that may be the easier ones to start off with to them.

**Comment by alissapajer** [comment]
@zeeiyerWork sounds good. @drostron @wemrysi and I can chat and figure out who wants to take which issues.
