### ISSUE TITLE
Remove the integration test spinner

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2513]
The integration test spinner (the thing that goes `[.............`) was required back in a day before the enlightenment of `logBuffered in Test := false`, which solves the problem in a better way.  We should just remove the spinner and allow specs2 to naturally output.

**Comment by rintcius** [comment]
Will need something more than just adding `logBuffered in Test := false`, I think? Because those ITs may run for `> travis_timeout`, so we have to make sure they output something (and at the moment we don't AFAIC since we have reduced the output recently via `xonly`)

**Comment by djspiewak** [comment]
@rintcius This is a good point.  I forgot that we simply don't output things on Travis unless they fail.  So we would need to keep the spinner on Travis at the very least.  That takes a lot of the wind out of this issue.

**Comment by alissapajer** [comment]
I think there still is value in seeing the test results streaming locally though. 

Also, why do we have test output omitted on travis? Is it just to keep the log small?

**Comment by djspiewak** [comment]
> Is it just to keep the log small?

Yep

**Comment by alissapajer** [comment]
So, I think it would be nice to see all the test output in travis for the full stack regression tests. If we enable specs2 timing then we can see how long the tests are taking (relative to each other), which would be useful information that takes too long to obtain locally on a regular basis.

Additionally the output for these tests isn't very long, just 2 lines per test. And we since we have separate jobs for each connector, each log file wouldn't be growing by that much.
