### ISSUE TITLE
Precog time and Quasar time impedance mismatch

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2564]
Breaking it down, quasar has three significant notions of time:

- `LocalTime` (it also has `LocalDate`, but I believe the former subsumes the latter)
- `Instant`
- `Duration`

Precog has the following *two* notions of time:

- `ZonedDateTime`
- `Period`

While `Period` aligns reasonably well with `Duration` (it's basically the `java.time` version of the same concept), `ZonedDateTime` doesn't align with `Instant` *or* `LocalTime`.  It's probably closest to `Instant`, but it's still not quite right.  This results in several issues with round-tripping data through mimir, as well as general problems with implementing certain time functions in the standard library.

In order to fix this, we need to do a couple things.  First, the `ZonedDateTime` case in `CValue` (and correspondingly, the `Column` specialization) needs to be converted to `Instant`.  Second, a new case needs to be added to `CValue` for `LocalTime` (and correspondingly, to `Column`).  This is likely to be severely disruptive, especially in `StringLib`, though fortunately most of those functions are now irrelevant.  There's a *ton* of boilerplate code that this touches and which will need to be updated.

**Comment by edmundnoble** [comment]
Here's what I've got out of this so far:
- Both Precog and Quasar are only using java.time, thankfully.
- `ZonedDateTime` is a combination of an `Instant` with a time zone; therefore Quasar appears to have no conception or use for time zones.
- `LocalTime` can't subsume `LocalDate`; `LocalTime` is only a wall clock time, but `LocalDate` is only a date. We'll need to add them as separate types to fix the impedance mismatch with Precog, especially because as-is `ZonedDateTime` is not only a combination of both a date and a time, but also a time zone.
- `Period` and `Duration` are both from java.time; the first is a difference in time, the second a difference in date. It looks like `Duration` is more useful, so it would make sense to rip out `Period` in favor of that, but they're orthogonal, so I'm not sure.

**Comment by edmundnoble** [comment]
Pinging @jdegoes 

There's an issue here. Quasar `Data` uses `java.time.Instant` for timestamps, which means no timezone information. There are `MapFuncCore`s `ExtractTimezone`, `ExtractTimezoneHour`, and `ExtractTimezoneMinute`. This means that information must be lost or corrupted during roundtrips to and from connectors, whether or not they have this timezone information. These will be impossible to implement for mimir and spark without choosing an arbitrary timezone because this ticket is for moving mimir to operate on `Instant` as well, and because spark operates on `Data` directly; this also means any data that moves through mimir will lose that information.

**Comment by jdegoes** [comment]
@edmundnoble A true SQL-style date/time must have information on time zone. So perhaps we should change the `Data` model to use something more SQL-ish.

**Comment by edmundnoble** [comment]
A summary of my thoughts and research on this so far:
- In terms of economy of concepts, we cover all of the area necessary in Data with Instant, ZonedDateTime, LocalDateTime.
- Postgres has dates, as well as times and timestamps, the latter two of which can have a time zone.
- MarkLogic uses xs:date, xs:time, and xs:dateTime, all of which can optionally have a time zone. Dates and times should both be able to roundtrip through ZonedDateTime and LocalDateTime.
- Couchbase uses strings to represent dates, times and timestamps, the latter two of which can have a time zone.
- Mongo's BSON datatype for dates has no concept of time zones. It's just a UTC timestamp. I believe this means we can't use BSON date for a ZonedDateTime or LocalDateTime, but we can for Instant.
- All of the connectors with date and time types are still a question. Do we allow access to those types? If so, how do we recognize a datetime as "really being" a date or a time, to preserve roundtrips? This may mean needing Instant, ZonedDateTime, LocalDateTime, ZonedTime, ZonedDate, LocalTime, and LocalDate, unfortunately.

**Comment by jdegoes** [comment]
👍

**Comment by edmundnoble** [comment]
Right, so per chatting with @jdegoes offline we're going to need to go with every permutation of the time and date types to prevent an impedance mismatch (specifically a roundtrip problem) with any of the databases listed above.

**Comment by djspiewak** [comment]
This isn't really tech debt.  Removing that label.

@edmundnoble Remember to move your tickets to "in progress" when you're working on them.

**Comment by edmundnoble** [comment]
Summary of the changes so far:
- I've removed `Date` and `Time` in favor of `LocalDate`, `OffsetDate`, `LocalTime` and `OffsetTime`. Several connectors (Couchbase, MarkLogic) support "date with time zone" and "time with time zone", so this is a move to make quasar cover their entire datetime/time/date surface area. This is despite times and dates on their own with time zone information being in general a bad idea to use; see https://www.postgresql.org/docs/9.1/static/datatype-datetime.html item 8.5.3 - perhaps some user education or warning is merited here.
-  `java.time.*` does not include `OffsetDate` despite it being implemented by some connectors, so it's been written as a pair of `LocalTime` and `ZoneOffset` in the `quasar` package with unit tests. If this becomes a performance problem in terms of allocation and indirection we can inline them into a single class. There may be a better place to put this and `DateTimeInterval` which is in the same package.
- `DateTime` types have been added, `LocalDateTime` and `OffsetDateTime`.
- `Interval` now supports days, months and years. The backing type has been changed from `java.time.Duration` to `DateTimeInterval`, another custom type with unit tests.
- I've removed `Timestamp`, because it's redundant with `OffsetDateTime` where the time zone is set to UTC. This will likely have ripple effects on the names of certain functionality in Quasar, especially `MapFunc`s.
- `SetTimeZone`, `SetTimeZoneHour`, `SetTimeZoneMinute` have been added as `MapFunc`s which are duals of `ExtractTimeZone`, etc. - solving #1985
- `TimeOfDay` has been substituted for `LocalTimeOfDay` and `OffsetTimeOfDay`. It doesn't make sense to grab a `LocalTime` out of an `OffsetTime` unless you know you're throwing away the time zone. It's also impossible to apply the time zone offset within `TimeOfDay` because there's no logic I can think of that can "roll over" safely. We could also provide an alternate variation of `TimeOfDay` which grabs the time out of `LocalDateTime` only, but I'm not sure about the power-to-weight ratio.

In terms of library functionality:
- Need to document the change to `StartOfDay`. It no longer returns `Timestamp` or even necessarily `OffsetDateTime`; it takes a date or datetime to the datetime at the start of that day. It will no longer add the UTC time zone, which would be the equivalent of returning `Timestamp`.
- Need to document the removal of the `Timestamp` function and the fact that `ToTimestamp` now makes an `OffsetDateTime` with UTC from a count of milliseconds. Maybe that means it needs a new name, `DateTimeFromMillis`?

In terms of tests:
- Need tests for all new `MapFunc`s introduced to be in `StdLibSpec`
- Need tests for some old `MapFunc`s in `StdLibSpec` (`ExtractTimeZone` and friends)
- Need integration tests for all connectors that ensure correct behavior w.r.t conversion between strings and the datetime/time/date types
- Need integration tests for `DateTimeInterval`'s new functionality w.r.t SQL^2
- Need example queries for QA to determine how the new functionality is working, need example queries which used to work but now will have different results

In terms of general remaining work:
- Need to update *all* connectors to support this functionality, mostly the new MapFuncs.
- Need to update the niflheim tests to make sure storage and retrieval works properly.
- Need to update niflheim's recognition of strings which are actually dates, times, datetimes or intervals in disguise.
- Need to update many of yggdrasil's tests and test data generators to get the new data types.
- Need to come up with hashcode algorithms for the new data types (very small item, should be very quick)
- Most of mimir's date and time functionality is not useful or mismatches MapFunc. However, it does contain some functionality which I think we should consider adding in the future; the rest will be removed outright.
    - There is no way to take out a part of a datetime/date/time type, modify it, then substitute the modified part into the same value. I believe the way to correct this is to extend the `SetTimeZone` etc. family of functions to cover the same parts as the `ExtractSeconds`, etc. family does. I've decided not to cover that with this issue, but to make a new one.
    - The `*between` functions are all redundant with the existence of an `Interval` type with `Extract` functionality.
    - Reductions on time and date need variations added for `DateTime` and `Offset*`... but do they even need to exist?

Mimir and all dependencies currently compile. I'll keep updating this striking things off.

**Comment by djspiewak** [comment]
@edmundnoble Outstanding work.  Regarding some of the connector implementations of specific functions, I would say that some of that work could probably be deferred in many cases in the interest of getting this into master sooner rather than later.  I'd definitely like to see most of the functions implemented in mimir (and obviously the corresponding detection in niflheim), but I think we can probably amortize the work required to bring all the other backends in sync.  Especially since most of the backends have other, larger things that aren't yet fully "quasar-compliant".
