### ISSUE TITLE
Design and expose purescript-appropriate parser API

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#2781]
We need to be able to invoke the new SQL² parser from within purescript passing some sort of parse tree visitor, so that the frontend is able to build their own AST.  Heads up, @garyb

**Comment by jdegoes** [comment]
I do not think that's a great idea (calling Scala.js from PureScript). It's a better idea to ensure there's a clear and precise grammar so it can be replicated in PureScript.

**Comment by djspiewak** [comment]
Other than aesthetic concerns, why is this not a good idea?  There aren't any generalized parser libraries for purescript that I'm aware of.  So we could create a clean and declarative grammar, but purescript wouldn't be able to reliably turn it into a parser.

**Comment by jdegoes** [comment]
The integration will be very messy because _every_ data structure will require a corresponding PureScript data type, e.g., whatever parses sequences in Scala is useless in PureScript; even the `Option` type will need stubbing, both constructors and deconstructors since some of these structures are pattern matched (or at least, end-of-the-world conversion). All this will greatly complicate and slow down the Scala code base, and impose a batch processor for a fixed (unannotated) tree on the front-end, which may have different needs (e.g. incremental parser for an annotated tree).

It sounds like a good idea in theory, but in practice it will be more trouble than running the same test suite on both parsers.

**Comment by djspiewak** [comment]
You misunderstand the level at which I want to do the integration.  The purescript-supplied visitor would be passed directly to the grammatical productions, meaning that no data structures whatsoever would be seen by purescript.  The only data it would see is a) values that the visitor created, b) strings, and c) some representation of gll's line information.  The *only* correspondence in datatypes would need to be on that third one.

**Comment by jdegoes** [comment]
@djspiewak You need representations for grammatical constructs like "zero or more", "optional", etc. Still leaves the other issues (parse mode, relevant annotations may differ, etc.).

I don't care either way if the front-end is on board with this plan.

**Comment by djspiewak** [comment]
> You need representations for grammatical constructs like "zero or more", "optional", etc

Only if you use EBNF.  If you use BNF, you don't need them.

> I don't care either way if the front-end is on board with this plan.

I'll make sure to drill into the specifics a bit more with them, so that we are sure we've adequately addressed these sorts of concerns.  The preliminary feedback on the idea thus far has been enthusiastic.
