### ISSUE TITLE
New Mongo plans more restrictive `Filter` conditions

### ISSUE THREAD

**Issue by jsantos17** [precog/quasar#2883]
Opening this for discussion. I talked earlier with @rintcius about this.

Consider the query:

`select * from a where "foo" ~ pattern or target ~ pattern`

Old Mongo yields the following workflow:

```
Workflow (crystallized):
Chain
├─ $ReadF(jps; zips)
├─ $SimpleMapF
│  ├─ Map
│  │  ╰─ Obj
│  │     ├─ Key(__tmp8: (new RegExp(_.pattern, "m")).test("foo"))
│  │     ├─ Key(__tmp9: _)
│  │     ├─ Key(__tmp10: _.pattern)
│  │     ├─ Key(__tmp11: _.target)
│  │     ╰─ Key(__tmp12: (new RegExp(_.pattern, "m")).test(_.target))
│  ╰─ Scope(Map())
├─ $MatchF
│  ╰─ Or
│     ├─ And
│     │  ├─ Doc
│     │  │  ╰─ Expr($__tmp9.pattern -> Type(Text))
│     │  ╰─ Doc
│     │     ╰─ Expr($__tmp8 -> Eq(Bool(true)))
│     ╰─ And
│        ├─ Doc
│        │  ╰─ Expr($__tmp10 -> Type(Text))
│        ├─ Doc
│        │  ╰─ Expr($__tmp11 -> Type(Text))
│        ╰─ Doc
│           ╰─ Expr($__tmp12 -> Eq(Bool(true)))
╰─ $ProjectF
   ├─ Name("value" -> "$__tmp9")
   ╰─ ExcludeId
```

New Mongo plans this as:

```
Workflow (crystallized):
Chain
├─ $ReadF(jps; zips)
├─ $SimpleMapF
│  ├─ Map
│  │  ╰─ Obj
│  │     ├─ Key(0: _.pattern)
│  │     ├─ Key(1: _.target)
│  │     ├─ Key(2: (new RegExp(_.pattern, "m")).test("foo"))
│  │     ├─ Key(3: (new RegExp(_.pattern, "m")).test(_.target))
│  │     ╰─ Key(src: _)
│  ╰─ Scope(Map())
├─ $MatchF
│  ╰─ And
│     ├─ Doc
│     │  ╰─ Expr($0 -> Type(Text))
│     ├─ Doc
│     │  ╰─ Expr($1 -> Type(Text))
│     ╰─ Or
│        ├─ Doc
│        │  ╰─ Expr($2 -> Eq(Bool(true)))
│        ╰─ Doc
│           ╰─ Expr($3 -> Eq(Bool(true)))
╰─ $ProjectF
   ├─ Name("value" -> "$src")
   ╰─ ExcludeId
```

If the `__tmp` names are matched with the names in new Mongo (i.e 0, 1, 2, 3) the plans are identical except for the boolean conditions. [This gist](https://gist.github.com/jsantos17/7477c99f5157b29e626c1dbc9a8cc855) contains the equivalence between projections in old Mongo and new Mongo.

Using the names I gave to each condition in that gist we can workout simplified the boolean expressions for each plan:

Old Mongo:

`(A AND B) OR (A AND C AND D)`

[Truth table](https://www.wolframalpha.com/input/?i=(A+AND+B)+OR+(A+AND+C+AND+D)+truth+table)

New Mongo:

`A AND C AND (B OR D)`
[Truth table](https://www.wolframalpha.com/input/?i=A+AND+C+AND+(B+OR+D)+truth+table)

As you can see the conditions are not equivalent. New Mongo's condition are more restrictive. The old Mongo plan allowed the LHS of `("foo" ~ pattern) OR (target ~ pattern)` to match even if `target` is not a string. Since this is a disjunction, as a user I'd expect the predicate to return true even if `target` is not a string and the LHS matches.

Branched of #2667

**Comment by rintcius** [comment]
It looks like we are using a form of 3-valued logic, though I also think it's not implemented correctly and consistently (or maybe I'm just unable to reverse-engineer the pattern behind it):

```
select val, true or val, val or true, false or val, val or false from `null/nulls`
Query time: 0.4s
{ "val": null, "1": true, "2": true, "3": null, "4": null }
{ "val": {  }, "1": true, "2": true, "3": {  }, "4": {  } }
{ "val": 1, "1": true, "2": true, "3": 1, "4": 1 }
```

I would have expected `false or val` and `val or false` to return `undefined` (i.e. `"3": {  }, "4": {  } `) for all 3 rows.

Also the constant variants look incorrect/inconsistent:
```
(v24.1.14) 💪 $ select true or 1 from zips
Quasar error: You provided a constant value Int(1) where we expected a Bool in Fix(Constant(Int(1)))
(v24.1.14) 💪 $ select false or 1 from zips
Query time: 0.0s
 value |
-------|
     1 |
```

Someone knows the specs for this?

**Comment by alissapajer** [comment]
We should get a confirmation from @jdegoes about the specs for this.

**Comment by djspiewak** [comment]
Based on precog's semantics for these operations:

**And**

|           | true      | false     | undefined |
| --------- | --------- | --------- | --------- |
| true      | true      | false     | undefined |
| false     | false     | false     | undefined |
| undefined | undefined | undefined | undefined |

**Or**

|           | true      | false     | undefined |
| --------- | --------- | --------- | --------- |
| true      | true      | true      | undefined |
| false     | true      | false     | undefined |
| undefined | undefined | undefined | undefined |

Any values which are not of boolean type would fall into the `undefined` category.  I do not believe that these are the semantics currently implemented by the mongo connector though.  Note that MRA doesn't say anything about booleans specifically.

**Comment by rintcius** [comment]
@djspiewak yeah, that's the semantics I expected. The implemented one seems to be closer to https://en.wikipedia.org/wiki/Three-valued_logic?oldformat=true#Kleene_and_Priest_logics with the difference that it (erroneously?) can return values other than `true`/`false`/`undefined` and that it can lead to a Quasar error.

Note that according to a later section on the same page, SQL also (attempts to) adhere to Kleene logic.

**Comment by djspiewak** [comment]
The Kleene logic in SQL comes from its `NULL` semantics, which are rather weird.  `NULL` in Quasar is simply a value, whereas in SQL it has magical (and inconsistent) semantics.  Quasar's `undefined` is distinct from `NULL`, whereas SQL inconsistently conflates the concepts.  In Quasar, the only elimination rule for `undefined` is `??`, while the only introduction is some sort of operation which is invalid on the underlying data (e.g. projecting a non-existent field, applying an arithmetic operation to a string, dividing by zero, etc).

Looping back to the issue you identified, I'm guessing that qscript is not inserting boolean guards correctly, which would lead to datastores like Mongo simply attempting to interpret boolean operations on non-boolean operands (whereas Mimir would have auto-filtered out those columns).

**Comment by jdegoes** [comment]
In order to support "lazy" disjunction with heterogeneous data, we need something like these semantics:

|           | true      | false     | undefined |
| --------- | --------- | --------- | --------- |
| true      | true      | false     | undefined |
| false     | false     | false     | false |
| undefined | undefined | false | undefined |

**Or**

|           | true      | false     | undefined |
| --------- | --------- | --------- | --------- |
| true      | true      | true      | true |
| false     | true      | false     | undefined |
| undefined | true | undefined | undefined |

This means `AND` and `OR` could be defined with `??` and a more primitive and/or operation.

The reason this is useful is it lets each branch of an `OR`, for example, explore different conditions for different schemas.

**Comment by djspiewak** [comment]
@jdegoes The problem is that the semantic you're suggesting (which really is a Kleene logic) falls apart with inconsistency when the full consequences are applied.  For example, imagine `foo.x || foo.y`, where `foo.y` contains *integers* but sometimes the field doesn't exist.  The `||` operator cannot be applied to numerics, and so any rows where `foo.y` exists, the results will be `undefined`.  *But* any rows where `foo.x` is true and `foo.y` does *not* exist, the results will be `true`.

That's a really weird truth table, and the only way to make it less weird is to say that `||` and `&&` can be applied to *any* type, and types which are not boolean map to `undefined`.  That feels like an incredibly weird semantic though.  `true || "fubar"` is not `true`: it should be `undefined`!  Adding polymorphism to these two operators seems confusing and costly for marginal benefit when we already have the `??` operator.

Speaking of which, remember that `undefined` is packed away in array structures, meaning that `??` cannot always "catch the exception".  You're proposing we add those same non-referentially-transparent semantics to `||` and `&&`.  It's relatively easy to explain to users "oh, you want to use `??` to explore heterogeneity, drive that operator as far *inside* the structure as possible".  It's much harder to say "and by the way, you have to do that with `&&` and `||` as well, even though you probably only cared about boolean expressions".

`??` is the effective equivalent of `catch` in SQL^2.  And that makes sense, because that's how the operator is defined.  But if you were defining a programming language, you wouldn't add `try`/`catch` semantics to your `&&` and `||` operators.  Short-circuiting, yes; `catch`, no.

So because of all that rabbit hole, I think it's a lot saner if we don't implement a three-value algebra, and instead let `undefined` eliminate booleans just as it does every other operation except `??`.

**Comment by jdegoes** [comment]
@djspiewak I'm very sympathetic, but nonetheless, I have seen many queries like:

```sql
... WHERE resident = "Y" OR resident = TRUE
```

These arise spontaneously without training users in the semantics of heterogeneity. Indeed, our SQL2 generator for the search card generates many queries like this, and would always return an empty result set under alternate semantics in the presence of any heterogeneity whatsoever.

I think we can also ask @damonLL and maybe @dugdun to chip in here. 

Short-circuiting, btw, would imply if you hit a `true` you'd stop even if the 2nd were `undefined`, which is also incompatible with the truth table you proposed. I don't think it's unusual to make the boolean disjunction / conjunction operators magical in languages, but I also share your concerns around user expectations with these operators being used on array elements.
