### ISSUE TITLE
MimirStdLibSpec failing for particular input

### ISSUE THREAD

**Issue by kciesielski** [precog/quasar#2923]
During one of my builds when writing PostgreSQL connector I stumbled upon such failing test:
```
[error] x any doubles (745 ms)
[error]  Falsified after 29 passed tests.
[error]  > ARG_0: 2.5013896297685519E18
[error]  > ARG_1: -7.722061907008521E15
[error]  > List(Dec(2493667567861543379)) doesn't have size 0 but size 1 (MimirStdLibSpec.scala:195)
```
https://travis-ci.org/quasar-analytics/quasar/jobs/286989508

**Comment by djspiewak** [comment]
I'm pretty sure this is a failure of `beCloseTo`.  Check it out:

```
@ 2.5013896297685519E18 - 7.722061907008521E15 
res1: Double = 2.4936675678615434E18
```

Mimir would have done this as `BigDecimal` addition due to the fact that it is receiving these values through `Data`.  Meaning that it would have gotten a more precise answer:

```
@ BigDecimal(2.5013896297685519E18) - BigDecimal(7.722061907008521E15) 
res2: BigDecimal = 2493667567861543379
```

The expectation is done in terms of `Double` though, meaning that the IEEE rounding takes effect.  So the answers are off by exactly **21**.

We can probably solve this problem by ensuring that all of the property tests within `StdLibSpec` use `BigDecimal` for their expectations.

**Comment by alissapajer** [comment]
When these (or any) tests fail in the master build, we don't publish the current release. So in order to have stable continuous delivery, we need to fix flaky tests like this.
