### ISSUE TITLE
Incorrect autojoin condition in many cases

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#2953]
In may cases when we generate a `ThetaJoin` in QScript as a result of `autojoin`, the join condition is incorrect (often non-existent, resulting in a costly cartesian). We need to improve our provenance handling and autojoin condition creation.

This is a contributing (if not the primary) cause of issues like #1929 and #2935, among others.

**Comment by zeeiyerWork** [comment]
I am including this a must-fix for Initial Production Rollout. since it seems the hope is to fix this and indirectly fix #1929 and #2935 - atleast the former is in the must-fix list for 5.0.0.

**Comment by alissapajer** [comment]
We've commonly come across queries that have an unnecessary join (created by `autojoin`) _and_ are returning incorrect results. We absolutely want to omit all unnecessary joins, but fixing this issue will at least allow such queries to return correct results.

**Comment by djspiewak** [comment]
@wemrysi When do we want to consider this "done"?

**Comment by wemrysi** [comment]
@djspiewak It could _probably_ be considered done now, though maybe a rigorous test would be if we could pass all the integration tests with `MinimizeAutoJoins` disabled.

**Comment by djspiewak** [comment]
@wemrysi Your call then on whether or not we close it.  I can see arguments for either approach.  :-)

**Comment by djspiewak** [comment]
Ooooh boy… https://gist.github.com/1d217da607d972c5d69f9ca33bf07298

Running the mimir integration tests with `MinimizeAutoJoins` disabled.  The exception you see throughout comes from here:

```scala
        case DerefObjectDynamic(source, ref) =>
          val l0 = composeSliceTransform2(source)
          val r0 = composeSliceTransform2(ref)

          l0.zip(r0) { (slice, derefBy) =>
            assert(derefBy.columns.size <= 1)
            derefBy.columns.headOption collect {
              case (ColumnRef(CPath.Identity, CString), c: StrColumn)       =>
                new DerefSlice(slice, { case row: Int if c.isDefinedAt(row) => CPathField(c(row)) })
            } getOrElse {
              slice
            }
          }
```

The assertion in question is failing.  This means two bad things.  First, `DerefObjectDynamic` is never something we should be generating, even when doing a ton of joining, because it's horrific and slow.  Second, it means that we were trying to interpret a `ProjectKey` where the `RightSide` corresponded to either a non-scalar value (an object or an array) or a heterogeneous value (i.e. a field that contains strings *and* booleans, or a field that contains numerics).

So definitely still generating bad join keys.
