### ISSUE TITLE
epic: Establish QSU

### ISSUE THREAD

**Issue by wemrysi** [precog/quasar#2984]
`QScriptUniform` (QSU) is new intermediate representation purpose-built for compiling from `LogicalPlan` to `QScript`.

---

Current integration test status (will be kept updated): 

- 😍 mimir: https://gist.github.com/5ee59c525f9bfc6ee19a783f1a40332a
- 😍 mongo: https://gist.github.com/2340acdba797c123d0cf0dd20dc3b9dd
- 😍 spark_local: https://gist.github.com/0a703c0e5bfcac2bcb60f30076703678

**Comment by alissapajer** [comment]
Issues in this epic with the `status: On hold` label are merged into the `qsu` branch but are not yet merged into `master`. These issues will be closed en masse when `qsu` is merged into `master`.

**Comment by alissapajer** [comment]
To clarify further, any issue that is fixed but tracks a user-facing preexisting bug will get the label `status: On hold` until the fix lands in `master`. Any issue that was created in order to track our progress implementing `QSU` itself will be closed when the implementation lands in the `qsu` branch.

**Comment by zeeiyerWork** [comment]
Makes sense - is consistent with what we did for next-major.
