### ISSUE TITLE
Extract a partial query evaluator out of Mimir

### ISSUE THREAD

**Issue by jedesah** [precog/quasar#3087]
It shouldn't be too much work to extract a meaningful in memory query evaluator for constant plans. Ideally, the code would be factored in way to achieve very good re-use between this new thing and the current Mimir connector. This code could potentially also be used by the current in memory filesystem implementation to replace it's extremely naive query evaluation.

**Comment by djspiewak** [comment]
To be more precise…  This would require a new implementation of `load`, which is to say, a secondary replacement for (or rather, additional implementation of) `VFSColumnarTableModule`.  Maybe an in-memory interpreter for `FreeVFS` would make sense, though it's hard to say.  This in turn would mean that we would need to abstract over cake instances, rather than just delegating to the concrete `Precog`.  The `Mimir` evaluator would need to be able to work with either of the two cakes transparently.
