### ISSUE TITLE
Structure editor queries produce exponential tree expansion

### ISSUE THREAD

**Issue by djspiewak** [precog/quasar#3188]
This is a continuation of #2775 (heads up, @garyb).  The query in question is this:

```sql
SELECT 
  MAP_CONCAT(t3, {"b": MAP_CONCAT(DELETE_KEY(t3.b, "c"), {"be": MAP_CONCAT(t3.b.be, t3.b.c) ?? t3.b.c}) ?? t3.b}) ?? t3
FROM 
  (
    SELECT 
      MAP_CONCAT(DELETE_KEY(t2, "c"), {"b": MAP_CONCAT(t2.b, {"c": MAP_CONCAT(t2.b.c, t2.c) ?? t2.c}) ?? {"c": t2.c}}) ?? t2
    FROM 
      (
        SELECT 
          MAP_CONCAT(t1, {"b": MAP_CONCAT(DELETE_KEY(t1.b, "innermost"), {"bd": MAP_CONCAT(t1.b.bd, t1.b.innermost) ?? t1.b.innermost}) ?? t1.b}) ?? t1 
        FROM 
          (
            SELECT 
              MAP_CONCAT(t0, {"b": MAP_CONCAT(DELETE_KEY(t0.b, "ba"), {"ba": DELETE_KEY(t0.b.ba, "innermost") ?? t0.b.ba, "innermost": MAP_CONCAT(t0.b.innermost, t0.b.ba.innermost) ?? t0.b.ba.innermost}) ?? t0.b}) ?? t0
            FROM :resource
            AS t0)
          AS t1) 
      AS t2) 
  AS t3
```

Dataset (represented by `:resource`) can be found here: https://gist.github.com/garyb/6ffc22924376c59ef28b128660371ae8

This produces [qscript](https://www.dropbox.com/s/8qrqx0i5icu4ui1/qscript.txt?dl=1) which contains almost 400,000 nodes, nearly all of which are contained in a single `FreeMap`.  The good news is that, relative to the number of nodes being produced, QSU is compiling and planning this query relatively rapidly.  The bad news is that it's still far too slow, broadly because the query explodes into something so huge.

We need to explore ways to bring this down, either by changing the query or by changing qscript in some ways.  As an example, most of the node explosion comes from the number of guards that are in play.  A trivial (though incorrect on some connectors) way to bring down the compilation and runtime (which dominates) of this query would be to disable typechecks.  A better way might be to introduce a specialized `Guard` node which represents a typecheck filter, where this new `Guard` has a single hole and a type, and it evaluates to `Undefined` if the type predicate is unmatched or to the hole if it *is* matched.  This would probably optimize a lot of queries, actually.

Also, just having a rewrite that collapses directly adjacent `Guard` nodes which have identical type predicates would probably help a fair bit.

Another way to bring down the number of nodes is to handle references better.  LP has to expand out all of the references found in the original query.  Many of them will end up as `Let` bindings, and QSU will collapse the ones that don't, but it's still really gnarly.  And at the end of the day, `FreeMap` doesn't have a way of encoding referenced results.  Having an encoding of `Let` in `FreeMap` would be very interesting, and could actually produce a rather significant performance boost in mimir (though I doubt it would help other connectors very much).

**Comment by djspiewak** [comment]
@jdegoes I'm curious as to your thoughts on this.

**Comment by jdegoes** [comment]
> We need to explore ways to bring this down, either by changing the query or by changing qscript in some ways.

In this case, **not** by changing the query, because such a small amount of SQL can be written by hand and should be handled properly by Quasar (one can argue the point when the front-end starts generating hundreds or thousands of lines of SQL, but this case is completely unambiguous IMO).

> And at the end of the day, FreeMap doesn't have a way of encoding referenced results. Having an encoding of Let in FreeMap would be very interesting, and could actually produce a rather significant performance boost in mimir (though I doubt it would help other connectors very much).

This seems interesting though I don't see how it would solve this problem (would it??).

> Also, just having a rewrite that collapses directly adjacent Guard nodes which have identical type predicates would probably help a fair bit.

👍 

> A better way might be to introduce a specialized Guard node which represents a typecheck filter, where this new Guard has a single hole and a type, and it evaluates to Undefined if the type predicate is unmatched or to the hole if it is matched. 

Or even annotate every node with the type and assume each connector will deal with it appropriately. We can always have helpers to "compile down" a type check into simple elements (conditional, `??`, and `TYPEOF`).

**Comment by djspiewak** [comment]
> In this case, not by changing the query, because such a small amount of SQL can be written by hand and should be handled properly by Quasar (one can argue the point when the front-end starts generating hundreds or thousands of lines of SQL, but this case is completely unambiguous IMO).

I definitely agree here.  What the structure editor generates is clearly valid SQL^2; it shouldn't result in trees which are orders of magnitude larger than the syntactic form.

> This seems interesting though I don't see how it would solve this problem (would it??).

It would for mimir, and it would instantaneously collapse the compilation time.  But I suspect it wouldn't help any other connector.

> Or even annotate every node with the type and assume each connector will deal with it appropriately. We can always have helpers to "compile down" a type check into simple elements (conditional, ??, and TYPEOF).

Annotation is harder than just introducing a new node, since that would require introducing `Cofree` in a number of places where we only have `Free`.  But I think the new derived node will at least give us a solid idea of the impact of this change.  @jedesah is up to speed and he'll be working on proofing this out.  If he's able to get a 2+ order of magnitude reduction in the number of `FreeMap` nodes (which I strongly suspect he will), then we know we're at least on the right track.

**Just to clarify requirements…**  I'm assuming that business requirements for the structure editor at depth 4 are compilation+evaluation in about 10-15 seconds, correct?  Or do we need to get it down tighter than that.  200s (where we are currently) is clearly insane, but how low do we actually need to get it *for 5.0*?

**Comment by jdegoes** [comment]
>  a) I know that the query is being automatically generated, and b) I am literally not above "rigged demo" techniques to make this feature work (at least for now). :-)

We can talk to @garyb. If there's a way to fix the query, it'd probably involve more SQL functions, and the tradeoff of implementing those versus optimizing should be considered. In any case, it's clear that if we can't handle this small query, there exists _sufficiently nested_ structure edits that while realistic to generate, will cause failure no matter what changes we make to query generation.

> It would for mimir, and it would instantaneously collapse the compilation time. But I suspect it wouldn't help any other connector.

Doing something just for Mimir is totally legit at this point, and of course the "instantaneous collapse" of compilation time sounds very useful. 😄 

> Or do we need to get it down tighter than that. 200s (where we are currently) is clearly insane, but how low do we actually need to get it for 5.0?

Since users don't have access to the structure editor in 4.2.x, I'm less concerned about its limitations than concerned about no regressing on demo queries and queries actually used by customers. In my view, we ship 5.0 when the latter milestone has been obtained. Likely at this point some structure edits will work, but probably not very deep edits.

**Comment by djspiewak** [comment]
Ok. My guess is that JR’s work will get us to what I’m describing. We’ll see though.

**Comment by jedesah** [comment]
So I think something as simple as:

```select DELETE_KEY(t0.a, "yy") from (select DELETE_KEY(t1, "tt") from :resource as t1) as t0```

illustrates the problem we are dealing with without having to wrap one's mind around thousands of nodes.

The above query produces this QScript:

```
Map
├─ ShiftedRead(/structure, ExcludeId)
╰─ Guard
   ├─ Guard
   │  ├─ ○
   │  ├─ Type(Obj(Map[], Some(Top)))
   │  ├─ ProjectKey
   │  │  ├─ DeleteKey
   │  │  │  ├─ ○
   │  │  │  ╰─ Constant(Str(tt))
   │  │  ╰─ Constant(Str(a))
   │  ╰─ Undefined
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ Guard
   │  ├─ ○
   │  ├─ Type(Obj(Map[], Some(Top)))
   │  ├─ DeleteKey
   │  │  ├─ ProjectKey
   │  │  │  ├─ DeleteKey
   │  │  │  │  ├─ ○
   │  │  │  │  ╰─ Constant(Str(tt))
   │  │  │  ╰─ Constant(Str(a))
   │  │  ╰─ Constant(Str(yy))
   │  ╰─ Undefined
   ╰─ Undefined
```

We can see how we are repeating the same expression twice, not to mention guarding more than we need to.

@djspiewak As you mentioned in your initial comment, I think the real solution here is introducing the possibility to reference previous expressions inside of a `FreeMap` (which btw we should rename to `Lambda` or `FuncExpr` or wtv, but something that says what it's meant to represent rather than how it's implemented). Right now this problem is surfacing because guards are ubiquitous, but it would surface with any non-unary `MapFunc`. Which makes me wonder why `Free[MapFunc, Hole]` was chosen in the first place. Did we not foresee that some of these expressions would get fairly complex and repeat themselves if represented this way? It seems like I may be I'm missing something here, especially since we have let expressions in `LogicalPlan`.

I agree though that a "filter Guard" node would, as far as I can tell, solve this problem. I do worry though that it's not the most generic fix and that it won't actually fix the runtime of Mongo if it depends on the derived implementation (which sounds like it kind of has to).

But as you mentioned, adding this new guard is a good stepping stone for confirming the hypothesis. I realize most of this is just saying in my own words what you've already written 😄. I guess my question to you is what are the implications of adding let bindings to `FreeMap`?

**Comment by jedesah** [comment]
@djspiewak Actually I just thought about it a little extra more 😄 and I think there is no way this query is going to generate a reasonable size QScript without `FreeMap` having some notion of referencing a previously computed value. The QScript generated by this query is just a single `Map` which makes sense since we are just reading from a single file. That means there is absolutely zero references to previously defined values in that entire QScript. This means that the five times we reference `t3` in the outer query, we are inlining EVERYTHING at each reference site and of course those inlined expressions contain 7 references to `t2` which itself gets inlined to the two inner queries and you see where this goes...

`Guard` definitely makes it worse because every time we `ProjectKey`, we add an extra reference, so it's more like we reference `t3` 25 times in the outer layer and each reference is the entire inlined inner 3 queries.

🤣 🤣  It's kind of hilarious actually

**Comment by djspiewak** [comment]
So this is definitely something we've talked about quite a bit.  Just adding let bindings to qscript was actually one of the options we played around with before we decided to go the QSU route.  The more restricted variant of that concept (adding let-bindings to `FreeMap`) is probably more reasonable, but it's still dicy.

As an example, one way this could be done is generalizing all of our `FreeMapA` usage to the following:

```scala
type RecFreeMapA[A] = Fix[Coproduct[FreeMapA, Const[A, ?], ?]]
```

Alternatively, `type RecFreeMapA[A] = HFree[MapFunc, A]`, assuming an `HFree` which embeds the free monad and free functor, much as `Free` embeds the free functor.

Encoding aside…  The real problem here is that it significantly complicates most connector implementations.  It's not straightforward for most connectors to save off previous results, so they would probably end up linearizing things anyway.  That's not the worst thing in the world, but it's more burden on them.  Mimir would certainly be able to benefit *significantly* from something like this, not just in an efficiency-of-tree standpoint but also in efficiently avoiding redundant computation, but that's one connector.  Maybe still worth doing, but only one connector.

Critically, anything like this is going to be a large change, and really can't make it for 5.0.  Adding a `Typecheck` derived mapfunc is definitely a stopgap, you're right, because the underlying problem of replication still remains just from the fact that SQL allows repeated subexpression references.  But it's probably a good stopgap *anyway*, since there are a lot of things we can do with a semantically more-specific node than `Guard` (Mimir can ignore most of them, for example), and it doesn't preclude doing let bindings down the road.

**Comment by jedesah** [comment]
I don't fully understand why a connector such as Mongo wouldn't be able to take advantage of let bindings to avoid recomputing things multiple times (like for map-reduce if not aggregation pipeline?) maybe I could bug someone to explain that to me one of these days.

I'll take your word that let bindings for 5.0 is not going to happen. My guess is that `Typecheck`alone won't go below 10 seconds for depth 4 and certainly forget about depth 5 😆.

**Comment by jdegoes** [comment]
MongoDB has let bindings but they are restricted in scope to essentially `MapFunc`. 

@jedesah's right, though, that let bindings can offer reuse at higher levels, such as computing a result, and storing it into a collection (or in memory) before further processing. 

In general I think all connectors can greatly benefit (from a performance standpoint) with first-class support for let bindings; and that all connectors will have to pay heavy taxes to leverage such support (but will benefit significantly enough to make it worthwhile).

**Comment by djspiewak** [comment]
I wasn't aware that aggregation pipelines had any notion of let-binding.  If they do, then yes, let-bindings become a much more interesting solution, but I was under the impression that they would only be encodable within a map-reduce.  Honestly, let-bindings probably already were the most interesting solution long-term, they're just a larger project to get done and hard to do incrementally.

To be more specific, @jdegoes, the let-bindings we're talking about would be restricted to `Free[MapFunc, A]` in scope.  Let-bindings at a larger level are generally handled pretty well by qscript's common source encoding, the problem is just that the common source encoding doesn't extend to within the freemap structure.

> I don't fully understand why a connector such as Mongo wouldn't be able to take advantage of let bindings to avoid recomputing things multiple times

Because in most connectors, freemaps are translated into trees of operations.  If the algebra that defines that tree in a particular connector does not define any notion of shared result or let-binding, then let bindings in freemap do exactly nothing for connectors other than create complexity.  With mimir, we can solve that expressiveness problem directly by simply adding a notion of shared result to its internal operation tree, but we don't have that option with other connectors.  In particular, if MongoDB doesn't support let-bindings in aggregation pipelines, then they really aren't that much of a win for that connector (since map-reduce is already very expensive for other reasons).

The only thing let-bindings would do for connectors which do not support them natively in their row operation pipelines would be to reduce the in-memory size of the freemap tree.  That alone might be a worthwhile goal, but it's unlikely to have the effect you are thinking of, since results would still be recomputed.

> My guess is that Typecheckalone won't go below 10 seconds for depth 4 and certainly forget about depth 5

Well, finding that out is literally the whole point of what you're doing.  :-)  I suspect it'll be a fair bit more than that (because we remove all of the doubling between operations, just not the cross-reference linearization), but we need to see for sure.  That's why we need to see a prototype of the `Typecheck` approach, so we can quickly get an idea of whether or not it's going to help enough for 5.0, and if we need to pivot to something else.

**Comment by jdegoes** [comment]
@djspiewak 

Let bindings are [documented here](https://docs.mongodb.com/manual/reference/operator/aggregation/let/).

**Comment by djspiewak** [comment]
Already found that page. See my edit. :-)

**Comment by djspiewak** [comment]
Unskulling this per @jdegoes.  We can ship 5.0 even with structure editor in this state.  Obviously doing better would be ideal, but it's no longer considered a show-stopper.

**Comment by jedesah** [comment]
So benchmark results are disappointing:

with new Typecheck node: 289.9s. 37180 typecheck nodes and 21365 guard nodes
without Typecheck node: 227.0s. 56686 guard nodes

I don't actually think that Typecheck makes it slower, it just goes to show the variability of this kind of benchmark. For reasons I don't understand, saw the Typecheck node do 195 seconds while video sharing with @djspiewak. Both times I was running on the battery and in the above measurements had wifi turned off.

I'll open a PR with typecheck since we said it was useful anyway.

**Comment by djspiewak** [comment]
So this cuts the number of `Guard`s in half without addressing the second-order case.  Did you measure the total number of nodes?  That's what's much more interesting to me than the number of typecheck or guard nodes.

Either way, based on the performance benchmark, and even taking into account the variability, I agree that we're going to have to do `Let` bindings to even fix this specific case.
