### ISSUE TITLE
Make the demo queries from #3250 more meaningful

### ISSUE THREAD

**Issue by alissapajer** [precog/quasar#3259]
The demo query data `demo/flights.data` has very few rows and so the queries on it in #3250 have only one row to sort or group. 

This issue is to add new integration tests with new extended data for these two cases. See PR comments for details.

**Comment by rabbitonweb** [comment]
@alissapajer I will assign this to myself. Please not however that other tests in `demo` have very big data sets, and `order by` is tested there ... extensively

**Comment by rabbitonweb** [comment]
@alissapajer the issue was created because you feel that sorting is not properly tested correct? 
i wonder if that is really needed, because sorting was extensively tested in oder tests (I was able to catch some weird mimir errors with sorting) 
also originally sorting was not even on the original queries
i just added them for determinism in tests
so tl;dr a) `ORDER BY` is extensively testes in other tests b) it was not  even needed in “Flights” demo queries
given the  above: should we really do #3259 ?
I’m not super against it, it just seems like a bit of waste, because it adds no value overall


[5:59] 
what do you think?

**Comment by rabbitonweb** [comment]
@alissapajer it's not a problem for me to create it (manner of 10 min work). I just wonder if it makes sense. Short 👍 (do it) 👎 (leave it) will suffice
